#!/usr/bin/env bash

# Show help message
show_help() {
  echo "Options:"
  echo "  -h, --help       Show this help message"
  echo "  -l, --list       List all touchpad devices"
  echo "  -e, --enable     Enable tap to click and natural scrolling"
  echo "  -d, --disable    Disable tap to click and natural scrolling"
  echo ""
  echo "Example:"
  echo "  touchpad_config -e 12"
}

# List devices
show_device_list() {
  xinput list
}

# Get touchpad device ID
get_touchpad_id() {
  local touchpad_id=$(xinput list | grep -i "touchpad" | grep -o "id=[0-9]\+" | cut -d'=' -f2)
  echo "$touchpad_id"
}

# Detect the touchpad driver
detect_touchpad_driver() {
  local driver=$(xinput list-props "$(get_touchpad_id)" | grep -q "Synaptics" && echo "Synaptics" || echo "libinput")
  echo "$driver"
}

# Enable tap to click and natural scrolling
enable_touchpad() {
  local id="$1"
  local driver="$2"
  case "$driver" in
    "Synaptics")
      xinput set-prop "$id" "Synaptics Tap Action" 0 0 0 0 1 3 2
      xinput set-prop "$id" "Synaptics Scrolling Distance" -55 -55
      echo "Tap to click enabled" 
      echo "Natural scrolling enabled." ;;
    "libinput")
      xinput set-prop "$id" "libinput Tapping Enabled" 1
      xinput set-prop "$id" "libinput Natural Scrolling Enabled" 1
      echo "Tap to click enabled" 
      echo "Natural scrolling enabled." ;;
    *) echo "Unsupported driver: $driver" ;;
  esac
}

# Disable tap to click and natural scrolling
disable_touchpad() {
  local id="$1"
  local driver="$2"
  case "$driver" in
    "Synaptics")
      xinput set-prop "$id" "Synaptics Tap Action" 0 0 0 0 0 0 0
      xinput set-prop "$id" "Synaptics Scrolling Distance" 1 1
      echo "Tap to click disabled"
      echo "Natural scrolling disabled." ;;
    "libinput")
      xinput set-prop "$id" "libinput Tapping Enabled" 0
      xinput set-prop "$id" "libinput Natural Scrolling Enabled" 0
      echo "Tap to click disabled"
      echo "Natural scrolling disabled." ;;
    *) echo "Unsupported driver: $driver" ;;
  esac
}

# Handle arguments
case "$1" in
  "-h" | "--help") show_help ;;
  "-l" | "--list") show_device_list ;;
  "-e" | "--enable") id=$(get_touchpad_id) && driver=$(detect_touchpad_driver) && enable_touchpad "$id" "$driver" ;;
  "-d" | "--disable")id=$(get_touchpad_id) && driver=$(detect_touchpad_driver) && disable_touchpad "$id" "$driver" ;;
  *) show_help && exit 1 ;;
esac
